### ISSUE TITLE
Add version guard around pragma "unused typedefs"

### ISSUE THREAD

**Issue by ChrisCummins** [ChrisCummins/msc-thesis#73]
```
[ 48%] Building CXX object libraries/stooling/src/CMakeFiles/stooling.dir/FixKernelParameterCallback.cpp.o
/home/chris/src/msc-thesis/skelcl/libraries/stooling/src/FixKernelParameterCallback.cpp:30:32: error: unknown option after ‘#pragma GCC diagnostic’ kind [-Werror=pragmas]
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
make[2]: *** [libraries/stooling/src/CMakeFiles/stooling.dir/FixKernelParameterCallback.cpp.o] Error 1
make[1]: *** [libraries/stooling/src/CMakeFiles/stooling.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ChrisCummins** [comment]
Offending pragma:

```
#pragma GCC diagnostic ignored "-Wunused-local-typedefs"
```

**Comment by ChrisCummins** [comment]
Fixed.
